flowchart TD
  P1["Page 1"]
  P2["Page 2"]
  P3["Page 3"]
  P4["Page 4"]
  P5["Page 5"]
  P6["Page 6"]
  P7["Page 7"]
  P8["Page 8"]
  P9["Page 9"]
  P10["Page 10"]
  P1 -->|"hide,"| P5
  P1 -->|"remain frozen in shock,"| P7
  P1 -->|"try and find the light switch,"| P9
  E2["THE END"]
  P2 --> E2
  E3["THE END"]
  P3 --> E3
  E4["THE END"]
  P4 --> E4
  P5 -->|"investigate the scream and search the house,"| P2
  P5 -->|"find a way out,"| P6
  E6["THE END"]
  P6 --> E6
  P7 -->|"stay and look for your mom,"| P8
  P7 -->|"decided to leave with your cousins,"| P3
  E8["THE END"]
  P8 --> E8
  P9 -->|"report him"| P4
  P9 -->|"ignore it,"| P10
  E10["THE END"]
  P10 --> E10
