flowchart TD
  P1["Page 1"]
  P2["Page 2"]
  P3["Page 3"]
  P4["Page 4"]
  P5["Page 5"]
  P6["Page 6"]
  P7["Page 7"]
  P8["Page 8"]
  P9["Page 9"]
  P10["Page 10"]
  P11["Page 11"]
  P12["Page 12"]
  P13["Page 13"]
  P14["Page 14"]
  P15["Page 15"]
  P16["Page 16"]
  P17["Page 17"]
  P18["Page 18"]
  P19["Page 19"]
  P20["Page 20"]
  P21["Page 21"]
  P1 -->|"Continue"| P2
  P2 -->|"take a nap? (You just travelled through time. You deserve a little rest.)"| P3
  P2 -->|"climb a nearby tree to get a better look at the area"| P4
  P2 -->|"hike around"| P5
  P3 -->|"go into the cave,"| P6
  P3 -->|"try to find the portal,"| P9
  P4 -->|"keep looking for the portal,"| P7
  P4 -->|"show your team the hook,"| P10
  P5 -->|"attack the velociraptor,"| P8
  P5 -->|"run and hide,"| P11
  E6["THE END"]
  P6 --> E6
  P7 -->|"trust the strangers,"| P16
  P7 -->|"turn back,"| P14
  E8["THE END"]
  P8 --> E8
  P9 -->|"touch the button"| P12
  P9 -->|"do not touch the button"| P13
  P10 -->|"lead,"| P15
  P10 -->|"let someone else lead,"| P17
  P11 -->|"jump off in North America,"| P20
  P11 -->|"jump off in India,"| P21
  E12["THE END"]
  P12 --> E12
  E13["THE END"]
  P13 --> E13
  E14["THE END"]
  P14 --> E14
  P15 -->|"try and help your teammate,"| P18
  P15 -->|"let your teammate perish and save yourself,"| P19
  E16["THE END"]
  P16 --> E16
  E17["THE END"]
  P17 --> E17
  E18["THE END"]
  P18 --> E18
  E19["THE END"]
  P19 --> E19
  E20["THE END"]
  P20 --> E20
  E21["THE END"]
  P21 --> E21
