flowchart TD
  P1["Page 1"]
  P2["Page 2"]
  P3["Page 3"]
  P4["Page 4"]
  P5["Page 5"]
  P6["Page 6"]
  P7["Page 7"]
  P8["Page 8"]
  P9["Page 9"]
  P10["Page 10"]
  P1 -->|"go through the hamster portal,"| P5
  P1 -->|"go through the galaxy portal,"| P7
  P1 -->|"go through the cat portal,"| P9
  E2["THE END"]
  P2 --> E2
  E3["THE END"]
  P3 --> E3
  E4["THE END"]
  P4 --> E4
  P5 -->|"go to the castle in the sky,"| P2
  P5 -->|"go to the castle in the forest,"| P6
  E6["THE END"]
  P6 --> E6
  P7 -->|"hide,"| P3
  P7 -->|"call for help,"| P8
  E8["THE END"]
  P8 --> E8
  P9 -->|"fight,"| P4
  P9 -->|"run,"| P10
  E10["THE END"]
  P10 --> E10
